### ISSUE TITLE
Shebang no longer supported?

### ISSUE THREAD

**Issue by ChildishGiant** [siffiejoe/lua-amalg#16]
The readme says you can prepend a shebang using -S or --shebang but both of these error.

WARNING amalg.lua: Unknown command line flag: -S
WARNING amalg.lua: Unknown command line flag: --shebang

**Comment by siffiejoe** [comment]
Those command line flags are rather new and not part of a tagged release to LuaRocks.org yet. I'll probably do a release soon, but in the meantime you can install the scm version using the `--dev` flag to `luarocks` (needs `git` in `PATH`).

**Comment by ChildishGiant** [comment]
I can't seem to use `--dev` (`Error: Invalid argument: unknown flag --dev. See --help.`) so I'll just wait until the next release. Thanks :smile:

**Comment by siffiejoe** [comment]
I've done a new release (v0.8).

**Comment by ChildishGiant** [comment]
All working now! :smile:
