### ISSUE TITLE
Is it possible to add a new feature for excluding some modules?

### ISSUE THREAD

**Issue by yuhangwang** [siffiejoe/lua-amalg#2]
Thank you for creating this amazing package. I especially like the automatic interception of the `require` command and bundle all needed modules effortlessly.  The following is my typical workflow

```
lua -lamalg pack.lua
lua amalg.lua -s pack.lua -c -o new.lua
```

However, sometimes I prefer not to include certain lua modules in my current project. Is it possible to add  a new feature for excluding some modules from the the amalg.cache? An example workflow can be

```
lua -lamalg pack.lua
lua amalg.lua -s pack.lua -exclude modue1 modue2 -c -o new.lua
```

**Comment by siffiejoe** [comment]
Certainly possible. For now, you can just edit the cache file `amalg.cache`.

**Comment by yuhangwang** [comment]
Thanks for the tip! I would be nice to have this feature natively supported by "lua-amalg".

**Comment by siffiejoe** [comment]
Has been implemented.

**Comment by yuhangwang** [comment]
The new feature is great. More than what I expected. Thank you!
