### ISSUE TITLE
Generated output file contains invalid Lua line: "#!/usr/bin/env lua"

### ISSUE THREAD

**Issue by drauschenbach** [siffiejoe/lua-amalg#4]
Generated output files start with this line which is not valid Lua:

```
#!/usr/bin/env lua
```

Lua VM's such as [GopherLua](https://github.com/yuin/gopher-lua) have no idea what to do with such lines.

The whole spirit of the Lua language is that it is embeddable in other programs. Therefore, making generated files dependent on Linux operating system shell features severely limits Amalg's usefulness.

**Comment by siffiejoe** [comment]
There is no default shebang line anymore if the main script doesn't include one.

**Comment by drauschenbach** [comment]
Nice!
